### ISSUE TITLE
Laboratory Work #0

### ISSUE THREAD

**Issue by mariiasirenko2** [OS-IS/ai201-sirenko#1]

**Comment by mariiasirenko2** [comment]
![Screenshot from 2024-09-21 08-14-28](https://github.com/user-attachments/assets/181d613e-b9ee-4aff-b33e-c92b84d9aba6)

Клонування репозиторію

**Comment by mariiasirenko2** [comment]
![photo_2024-09-21_09-04-00](https://github.com/user-attachments/assets/794f41b7-2f6b-4418-be9a-9a2520d961a2)

Оновлення репозиторію за допомогою токена

**Comment by mariiasirenko2** [comment]
![Screenshot from 2024-09-21 09-14-36](https://github.com/user-attachments/assets/f5bee70b-14c9-4f8e-b2aa-5a01a7fbcddc)
Клонування репозиторію за допомогою SSH

**Comment by oleksandrblazhko** [comment]
Рішення прийнято.
Оцінка = 5 балів.
Дякую
