### ISSUE TITLE
Control Work # 0

### ISSUE THREAD

**Issue by oleksandrblazhko** [OS-IS/ai201-sirenko#3]
Правильна відповідь на контрольне запитання дозволить вам отримати додаткові 2 бали 
до балів за виконання лабораторної роботи, якщо ви виявите бажання надати таку відповідь.
Відповідайте на запитання через коментар.

Запитання
2) Відомо, що Git-система контроля версій використовує поняття “гілка” (branch). 
Поясніть, будь ласка, як використання такої “гілки” 
може підвищити безпеку процесів створення програмного продукту?

**Comment by mariiasirenko2** [comment]
1) **Ізольованість змін**. Кожна гілка діє як окреме середовище для роботи над новим функціоналом, що дозволяє  вносити зміни, не впливаючи на main (з стабільним кодом)
2) **Захист main від несанкціонованих\непротестованих змін**. PR чи MR дозволяють перевіряти і затверджувати зміни перед їх злиттям в основну гілку. Це може бути представлено у виді списку правил, наприклад: рівень покриття тестами, проходження тестів, зелений пайплайн, апруви від затверджениз користувачів, тощо
3) **Права доступу та захист гілок**.  Доступ до основної гілки може бути обмеженим для кількох ключових розробників, що знижує ризик випадкових або небажаних змін у важливому коді. Protected гілки, що захищені від оновлень
4) **Збережена історія змін**, що сприяє кращій прозорості та можливості відкотитися до безпечної версії у разі помилки.
5) **Тестування**. перед мержанням нову функціональність в основну гілку, її можна ретельно протестувати в окремій гілці. Це знижує ймовірність внесення небезпечного або некоректного коду в стабільну версію продукту.

**Comment by oleksandrblazhko** [comment]
Рішення прийнято.
Оцінка = 2 бали
Дякую.
